### ISSUE TITLE
Fonts don't download properly in dev mode

### ISSUE THREAD

**Issue by DanielOaks** [khlieng/dispatch#2]
Hi! While trying to run this software in dev mode (running `gulp` at the same time as required in the readme), the fonts don't seem to download or display properly. This results in things like the icons in the lower-left and top-right not displaying correctly.

I've got a screenshot of this on Chrome, along with the errors in the console pointing towards the issue:
<img width="1372" alt="screen shot 2016-12-12 at 2 30 49 pm" src="https://cloud.githubusercontent.com/assets/251281/21088115/03318c6e-c078-11e6-9fdb-1b60fe9b2f6b.png">

I'll take a look at this myself, though I'm not too familiar with gulp and all.

Thanks a bunch for releasing this by the way, excited to have a great-looking Go IRC web client :)

-------

*edit:* As a note, running the `gulp build` and running Dispatch in regular, non-dev mode shows the fonts without an issue.

**Comment by khlieng** [comment]
This happens because the dispatch server itself doesn't serve the static assets in dev mode, they get served through gulp so that the webpack hot reloading stuff works. The gulp dev task starts a server listening on port 3000, which is what you need to access the client through. 

There are also assumptions made that the dispatch server will be listening on port 1337 so that the gulp server and the client knows where to find it :)

**Comment by DanielOaks** [comment]
Ah I see, that makes sense. In that case, feel free to ignore/close #3 if you'd like, since it's likely a bit of a hacky way to fix it in that case.
