### ISSUE TITLE
Issues connecting to an Oragono server

### ISSUE THREAD

**Issue by prologic** [khlieng/dispatch#6]
I haven't spent a lot of time debugging this but dispatch silently refuses to connect to an Oragono server (https://github.com/oragono/oragono)

**Comment by DanielOaks** [comment]
Testing here, it looks like Dispatch silently disconnects on TLS errors (such as connecting to a server with a self-signed TLS cert). If possible, displaying an error message on TLS cert errors would be great! It might be worth doing something like having a checkbox to allow self-signed certs on a per-server basis, since a fair number of real-world IRC networks out there today use self-signed (or at least not really verifiable) certificates.

**Comment by prologic** [comment]
Yeah agreed. Or even a simple popup javascript dialog/warning. "Are you sure you want to continue? The server reports a self-signed cert with fingerprint blah"

**Comment by prologic** [comment]
Hmm for some reason even without selecting SSL in the Dispatch UI this also doesn't work :/ I'll have to enable debugging and poke around :/

**Comment by khlieng** [comment]
Connecting without SSL works fine for me, are you running oragono on a different port?

**Comment by prologic** [comment]
Nope standard 6667 and 6697 for TLS

**Comment by DanielOaks** [comment]
Any chance you could make a packet capture of this or something similar? I'm not able to repro this here either. If you need any help with this, feel free to pop into the #oragono channel on Freenode [[link]](https://www.irccloud.com/invite?channel=%23oragono&hostname=irc.freenode.net&port=6697&ssl=1) and I can go through it a bit more with you so we can work out what's going on

**Comment by prologic** [comment]
I think we worked this one out; TL;DR network issue and bug in Docker 17.03-ce (fixed in 17.06-ce)
